version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
